services:
  kafka-controller-1:
    image: apache/kafka:3.8.1
    container_name: kafka-controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLE: controller
      KAFKA_LISTENER: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093, #2@kafka-controller-2:9093,3@kafka-controller-3:9093
    networks:
      dataOps:
    volumes:
      - controller_data_1:/var/lib/kafka/data


  kafka-controller-2:
    image: apache/kafka:3.8.1
    container_name: kafka-controller-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLE: controller
      KAFKA_LISTENER: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093, 2@kafka-controller-2:9093,3@kafka-controller-3:9093
    networks:
      dataOps:
    volumes:
      - controller_data_2:/var/lib/kafka/data
